---
title: "data-access"
author: "Brian Mahardja"
date: "11/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Demo of the pins package

```{r}
library(pins)
library(tidyverse)

delta_sites_edi <- pins::pin('https://portal.edirepository.org/nis/dataviewer?packageid=edi.233.2&entityid=6a82451e84be1fe82c9821f30ffc2d7d')
delta_sites <- readr::read_csv(delta_sites_edi, show_col_types = FALSE)

```

## Resolving data with contentid

```{r}
library(contentid)

delta_catch_edi <- 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.233.2&entityid=015e494911cf35c90089ced5a3127334'
delta_taxa_edi <- 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.233.2&entityid=0532048e856d4bd07deea11583b893dd'
delta_effort_edi <- 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.233.2&entityid=ace1ef25f940866865d24109b7250955'
delta_sites_edi <- 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.233.2&entityid=6a82451e84be1fe82c9821f30ffc2d7d'

delta_catch_id<-store(delta_catch_edi)

delta_catch_id

retrieve(delta_catch_id)

delta_catch<-read_csv(retrieve(delta_catch_id), show_col_types=FALSE)

delta_catch_file<-contentid::resolve(delta_catch_id,store=TRUE)

delta_catch2<-read_csv(delta_catch_file, show_col_types=FALSE)


```

